# Generated by Django 4.0.4 on 2022-07-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(choices=[('Labcorp', 'Labcorp'), ('Sevita', 'Sevita'), ('Cross Country', 'Cross Country'), ('Childrens', 'Childrens'), ('R1 RCM', 'R1 RCM')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subaccount_name', models.CharField(max_length=200)),
                ('subaccount_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.IntegerField()),
                ('client_mailbox', models.EmailField(max_length=254, unique=True)),
                ('reminder_email_needed', models.BooleanField()),
                ('first_reminder_day', models.CharField(blank=True, choices=[('Day 0', 'Day 0'), ('Day 1', 'Day 1'), ('Day 2', 'Day 2'), ('Day 3', 'Day 3'), ('Day 4', 'Day 4'), ('Day 5', 'Day 5'), ('Day 6', 'Day 6')], max_length=50, null=True)),
                ('second_reminder_day', models.CharField(blank=True, choices=[('Day 0', 'Day 0'), ('Day 1', 'Day 1'), ('Day 2', 'Day 2'), ('Day 3', 'Day 3'), ('Day 4', 'Day 4'), ('Day 5', 'Day 5'), ('Day 6', 'Day 6')], max_length=50, null=True)),
                ('third_reminder_day', models.CharField(blank=True, choices=[('Day 0', 'Day 0'), ('Day 1', 'Day 1'), ('Day 2', 'Day 2'), ('Day 3', 'Day 3'), ('Day 4', 'Day 4'), ('Day 5', 'Day 5'), ('Day 6', 'Day 6')], max_length=50, null=True)),
                ('clientname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.clients')),
                ('subaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.subaccount')),
            ],
        ),
    ]
