# Generated by Django 4.0.4 on 2022-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('service1', 'service1'), ('service2', 'service2'), ('service3', 'service3')], max_length=225)),
            ],
        ),
    ]
